project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - tutorials/*.qmd
    - appendix/*.qmd

website:
  title: "R for Population Health Research"
  search: true
  reader-mode: true
  repo-url: https://github.com/r-pophealth-research/online-course
  site-url: https://r-pophealth-research.github.io/online-course
  repo-actions: []
  navbar:
    background: primary
  sidebar:
    style: floating
    contents:
      - index.qmd
      - tutorials/data_types.qmd
      - tutorials/data_structures.qmd
      - tutorials/functions_packages.qmd
      - tutorials/data_exploration.qmd
      - tutorials/data_manipulation.qmd
      - tutorials/data_visualizations.qmd
      - tutorials/descriptive_statistics.qmd
      - tutorials/statistical_analyses.qmd
      - section: "Appendix"
        contents:
          - appendix/install_r_rstudio.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-overflow: wrap
    engine: knitr
    execute:
      eval: false

# Bundle data and images with the site so WebR can access them
resources:
  - data/
  - tutorials/images/

webr:
  show-startup-message: true
  channel-type: post-message

filters:
  - webr
